site_name: Apuntes DWCSS
site_description: Apuntes módulo 2ºDAW DWCSS

# Tema
theme:
  name: material
  language: es
  palette:
    - scheme: default
      toggle:
        icon: material/weather-sunny
        name: Cambiar a modo oscuro
    - scheme: slate
      toggle:
        icon: material/weather-night
        name: Cambiar a modo claro

  features:
    #    - navigation.tabs
    - navigation.expand
    - navigation.top
    - search.highlight
    - content.code.copy

# Navegación
nav:
  - Variables en JS: 01_variables.md
  - Asincronía en JS: Programación Asíncrona.md
  - Manipulación del DOM: Manipulación del DOM.md
  - Temporal API: Temporal API.md

# Extensiones básicas
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
      linenums: true
  - pymdownx.inlinehilite
  - pymdownx.tabbed:
      alternate_style: true
  - tables
  - attr_list
# Plugin de búsqueda
plugins:
  - search:
      lang: es
