site_name: Apuntes DWCSS
site_description: Apuntes módulo 2ºDAW DWCSS

theme:
  name: material
  language: es
  font: false # IMPORTANTE: Evita que busque fuentes en Google Fonts
  palette:
    - scheme: default
      toggle:
        icon: material/weather-sunny
        name: Cambiar a modo oscuro
    - scheme: slate
      toggle:
        icon: material/weather-night
        name: Cambiar a modo claro
  features:
    - navigation.expand
    - navigation.top
    - search.highlight
    - content.code.copy

# OBLIGATORIO para funcionamiento offline (index.html en lugar de carpetas)
use_directory_urls: false

# Navegación
nav:
  - Variables en JS: Types-Variables.md
  - HTML5 + Formularios: HTML-JS-forms.md
  - Expresiones Regulares en JS: Regexpr.md
  - Spread y Destructuring: Spread-Destructuring.md
  - Asincronía en JS: Async.md
  - Manipulación del DOM: DOM.md
  - Eventos en JS: Events.md
  - APIs REST en JS: REST.md
  - JSON en JS: JSON.md
  - Cookies vs LocalStorage: Cookies-LocalStorage.md
  - Date en JS: Date.md
  - Temporal API: Temporal-API.md
  - jQuery + AJAX: jQuery-AJAX.md
  - React:
      - Introducción: react/introduccion.md
      - Componentes y Props: react/componentes.md
      - JSX: react/jsx.md
      - Hooks Básicos: react/hooks-basicos.md
      - Hooks Avanzados: react/hooks-avanzados.md
      - Custom Hooks: react/custom-hooks.md
      - React Router: react/react-router.md
      - Formularios: react/formularios.md
      - Eventos y Buenas Prácticas: react/eventos-practicas.md
      - Ecosistema y Conclusión: react/ecosistema.md



markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
      linenums: true
  - pymdownx.inlinehilite
  - pymdownx.tabbed:
      alternate_style: true
  - tables
  - attr_list

plugins:
  - search:
      lang: es
  - offline
