site_name: Apuntes DWCSS
site_description: Apuntes módulo 2ºDAW DWCSS

# Tema
theme:
  name: material
  language: es
  palette:
    - scheme: default
      toggle:
        icon: material/weather-sunny
        name: Cambiar a modo oscuro
    - scheme: slate
      toggle:
        icon: material/weather-night
        name: Cambiar a modo claro

  features:
    #    - navigation.tabs
    - navigation.expand
    - navigation.top
    - search.highlight
    - content.code.copy
# use_directory_urls: false

# Navegación
nav:
  - Variables en JS: Types-Variables.md
  - HTML5 + Formularios: HTML-JS-forms.md
  - Expresiones Regulares en JS: Regexpr.md
  - Spread y Destructuring: Spread-Destructuring.md
  - Asincronía en JS: Async.md
  - Manipulación del DOM: DOM.md
  - Eventos en JS: Events.md
  - APIs REST en JS: REST.md
  - JSON en JS: JSON.md
  - Cookies vs LocalStorage: Cookies-LocalStorage.md
  - Temporal API: Temporal-API.md
  - jQuery + AJAX: jQuery-AJAX.md

# Extensiones básicas
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
      linenums: true
  - pymdownx.inlinehilite
  - pymdownx.tabbed:
      alternate_style: true
  - tables
  - attr_list
# Plugin de búsqueda
plugins:
  #  - offline
  - search:
      lang: es
